/** @file protocol.h
 *
 * Keymap for the MCU to IO protocol.
 *
 * @author Jonathan Pallant <github@thejpster.org.uk>
 * @copyright 2019 Jonathan Pallant
 * @licence MIT or Apache 2.0 at your option.
 */

#define KEYPRESS_F9 0x01
#define KEYPRESS_ALTRIGHT 0x02
#define KEYPRESS_F5 0x03
#define KEYPRESS_F3 0x04
#define KEYPRESS_F1 0x05
#define KEYPRESS_F2 0x06
#define KEYPRESS_F12 0x07
#define KEYPRESS_CONTROLRIGHT 0x08
#define KEYPRESS_F10 0x09
#define KEYPRESS_F8 0x0A
#define KEYPRESS_F6 0x0B
#define KEYPRESS_F4 0x0C
#define KEYPRESS_TAB 0x0D
#define KEYPRESS_BACKTICK 0x0E
#define KEYPRESS_WINDOWSLEFT 0x0F
#define KEYPRESS_WINDOWSRIGHT 0x10
#define KEYPRESS_ALTLEFT 0x11
#define KEYPRESS_SHIFTLEFT 0x12
#define KEYPRESS_MENUS 0x13
#define KEYPRESS_CONTROLLEFT 0x14
#define KEYPRESS_Q 0x15
#define KEYPRESS_KEY1 0x16
#define KEYPRESS_NUMPADSLASH 0x17
#define KEYPRESS_NUMPADENTER 0x18
#define KEYPRESS_END 0x19
#define KEYPRESS_Z 0x1A
#define KEYPRESS_S 0x1B
#define KEYPRESS_A 0x1C
#define KEYPRESS_W 0x1D
#define KEYPRESS_KEY2 0x1E
#define KEYPRESS_ARROWLEFT 0x1F
#define KEYPRESS_HOME 0x20
#define KEYPRESS_C 0x21
#define KEYPRESS_X 0x22
#define KEYPRESS_D 0x23
#define KEYPRESS_E 0x24
#define KEYPRESS_KEY4 0x25
#define KEYPRESS_KEY3 0x26
#define KEYPRESS_INSERT 0x27
#define KEYPRESS_DELETE 0x28
#define KEYPRESS_SPACEBAR 0x29
#define KEYPRESS_V 0x2A
#define KEYPRESS_F 0x2B
#define KEYPRESS_T 0x2C
#define KEYPRESS_R 0x2D
#define KEYPRESS_KEY5 0x2E
#define KEYPRESS_ARROWDOWN 0x2F
#define KEYPRESS_ARROWRIGHT 0x30
#define KEYPRESS_N 0x31
#define KEYPRESS_B 0x32
#define KEYPRESS_H 0x33
#define KEYPRESS_G 0x34
#define KEYPRESS_Y 0x35
#define KEYPRESS_KEY6 0x36
#define KEYPRESS_ARROWUP 0x37
#define KEYPRESS_PAGEDOWN 0x38
#define KEYPRESS_PAGEUP 0x39
#define KEYPRESS_M 0x3A
#define KEYPRESS_J 0x3B
#define KEYPRESS_U 0x3C
#define KEYPRESS_KEY7 0x3D
#define KEYPRESS_KEY8 0x3E
#define KEYPRESS_COMMA 0x41
#define KEYPRESS_K 0x42
#define KEYPRESS_I 0x43
#define KEYPRESS_O 0x44
#define KEYPRESS_KEY0 0x45
#define KEYPRESS_KEY9 0x46
#define KEYPRESS_FULLSTOP 0x49
#define KEYPRESS_SLASH 0x4A
#define KEYPRESS_L 0x4B
#define KEYPRESS_SEMICOLON 0x4C
#define KEYPRESS_P 0x4D
#define KEYPRESS_MINUS 0x4E
#define KEYPRESS_QUOTE 0x52
#define KEYPRESS_BRACKETSQUARELEFT 0x54
#define KEYPRESS_EQUALS 0x55
#define KEYPRESS_CAPSLOCK 0x58
#define KEYPRESS_SHIFTRIGHT 0x59
#define KEYPRESS_ENTER 0x5A
#define KEYPRESS_BRACKETSQUARERIGHT 0x5B
#define KEYPRESS_BACKSLASH 0x5D
#define KEYPRESS_BACKSPACE 0x66
#define KEYPRESS_NUMPAD1 0x69
#define KEYPRESS_NUMPAD4 0x6B
#define KEYPRESS_NUMPAD7 0x6C
#define KEYPRESS_NUMPAD0 0x70
#define KEYPRESS_NUMPADPERIOD 0x71
#define KEYPRESS_NUMPAD2 0x72
#define KEYPRESS_NUMPAD5 0x73
#define KEYPRESS_NUMPAD6 0x74
#define KEYPRESS_NUMPAD8 0x75
#define KEYPRESS_ESCAPE 0x76
#define KEYPRESS_NUMPADLOCK 0x77
#define KEYPRESS_F11 0x78
#define KEYPRESS_NUMPADPLUS 0x79
#define KEYPRESS_NUMPAD3 0x7A
#define KEYPRESS_NUMPADMINUS 0x7B
#define KEYPRESS_NUMPADSTAR 0x7C
#define KEYPRESS_NUMPAD9 0x7D
#define KEYPRESS_SCROLLLOCK 0x7E
#define KEYPRESS_F7 0x7F

#define KEYPRESS_KEYDOWN 0x00
#define KEYPRESS_KEYUP 0x80

/**************************************************
* End of file
***************************************************/
