#!/usr/bin/env python3

import serial
import sys
import time
file = sys.argv[2]
contents = open(file, "rb").read()
s = serial.Serial(sys.argv[1], 115200)
for b in contents:
	byte = bytes([b])
	print("Byte: {!r}".format(byte))
	s.write(byte)
	time.sleep(0.01)
if "--run" in sys.argv:
    s.write(b"RUN\r")
print("Done!\n")
